### PR TITLE
Fix the public device url

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch

### CODE REVIEW

**Review by sradevski — APPROVED** [review]
Should't expose work?

**Comment by thgreasi** [comment]
I think not, since the docker compose docs mention:
> Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.

See: https://docs.docker.com/compose/compose-file/compose-file-v2/#expose

I think that this was just bad copy paste from the multicontainer-getting-started, where we use a proxy and do not server from the ui container directly.
See: https://github.com/balena-io-examples/multicontainer-getting-started/blob/89ae9a1f756843db93cf0fa02ce7f2c4eb4db6ea/docker-compose.yml#L7-L13

**Comment by sradevski** [comment]
@thgreasi For some reason I had the impression that `expose <x>`  is the equivalent of `port <x>:<y>`, but it seems I was wrong :)

**Comment by thgreasi** [comment]
Well, you can't keep all the docs in mind...
I'm re-learning this every few months :)

**Pull request merged**
